"""Upload Audit

Revision ID: 16f39eb10740
Revises: 98cf2878361d
Create Date: 2025-10-28 15:50:42.060886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f39eb10740'
down_revision = '98cf2878361d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('last_update_date', sa.DateTime(), nullable=False))
    op.add_column('upload', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('upload', sa.Column('last_update_by', sa.String(length=200), nullable=False))
    op.add_column('upload', sa.Column('created_by', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'created_by')
    op.drop_column('upload', 'last_update_by')
    op.drop_column('upload', 'created_date')
    op.drop_column('upload', 'last_update_date')
    # ### end Alembic commands ###
