"""Add size to upload file

Revision ID: 1fe8bdf14c04
Revises: 0b5baa75372e
Create Date: 2024-08-05 14:34:23.123981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe8bdf14c04'
down_revision = '0b5baa75372e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_file', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_file', 'size')
    # ### end Alembic commands ###
