"""UploadData Audit

Revision ID: 6feaf93cbad3
Revises: 16f39eb10740
Create Date: 2025-10-28 15:51:26.727726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feaf93cbad3'
down_revision = '16f39eb10740'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_data', sa.Column('last_update_date', sa.DateTime(), nullable=False))
    op.add_column('upload_data', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('upload_data', sa.Column('last_update_by', sa.String(length=200), nullable=False))
    op.add_column('upload_data', sa.Column('created_by', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_data', 'created_by')
    op.drop_column('upload_data', 'last_update_by')
    op.drop_column('upload_data', 'created_date')
    op.drop_column('upload_data', 'last_update_date')
    # ### end Alembic commands ###
