"""Study Audit

Revision ID: 98cf2878361d
Revises: 151f1467fe64
Create Date: 2025-10-28 15:47:43.257237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cf2878361d'
down_revision = '151f1467fe64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study', sa.Column('last_update_date', sa.DateTime(), nullable=False))
    op.add_column('study', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('study', sa.Column('last_update_by', sa.String(length=200), nullable=False))
    op.add_column('study', sa.Column('created_by', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study', 'created_by')
    op.drop_column('study', 'last_update_by')
    op.drop_column('study', 'created_date')
    op.drop_column('study', 'last_update_date')
    # ### end Alembic commands ###
