"""UploadFile Audit

Revision ID: b98a2d011f66
Revises: 6feaf93cbad3
Create Date: 2025-10-28 15:51:59.889718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98a2d011f66'
down_revision = '6feaf93cbad3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_file', sa.Column('last_update_date', sa.DateTime(), nullable=False))
    op.add_column('upload_file', sa.Column('created_date', sa.DateTime(), nullable=False))
    op.add_column('upload_file', sa.Column('last_update_by', sa.String(length=200), nullable=False))
    op.add_column('upload_file', sa.Column('created_by', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_file', 'created_by')
    op.drop_column('upload_file', 'last_update_by')
    op.drop_column('upload_file', 'created_date')
    op.drop_column('upload_file', 'last_update_date')
    # ### end Alembic commands ###
