"""Upload deleted audit

Revision ID: d1cb89a5e9e5
Revises: b98a2d011f66
Create Date: 2025-11-03 15:29:52.929584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1cb89a5e9e5'
down_revision = 'b98a2d011f66'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('deleted_date', sa.DateTime(), nullable=True))
    op.add_column('upload', sa.Column('deleted_by', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'deleted_by')
    op.drop_column('upload', 'deleted_date')
    # ### end Alembic commands ###
